CREATE TABLE `tbl_other_information` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `hasthirddegree` bit(1) NOT NULL DEFAULT 0,
  `hasfourthdegree` bit(1) NOT NULL DEFAULT 0,
  `relateddetails` varchar(50),
  `wasguilty` bit(1) NOT NULL DEFAULT 0,
  `guiltydetails` varchar(50),
  `wascharged` bit(1) NOT NULL DEFAULT 0,
  `datefiled` date NOT NULL DEFAULT 0,
  `casestatus` varchar(50),
  `wasconvicted` bit(1) NOT NULL DEFAULT 0,
  `convicteddetails` varchar(50),
  `wasseparated` bit(1) NOT NULL DEFAULT 0,
  `separateddetails` varchar(50),
  `wascandidate` bit(1) NOT NULL DEFAULT 0,
  `candidatedetails` varchar(50),
  `resigned` bit(1) NOT NULL DEFAULT 0,
  `resigneddetails` varchar(50),
  `immigrant` bit(1) NOT NULL DEFAULT 0,
  `immigrantcountry` varchar(100),
  `isindigenous` bit(1) NOT NULL DEFAULT 0,
  `indigenousspecify` varchar(50),
  `isdifferentlyabled` bit(1) NOT NULL DEFAULT 0,
  `differentlyabledspecify` varchar(50),
  `issoloparent` bit(1) NOT NULL DEFAULT 0,
  `soloparentspecify` varchar(50),
  `Emp_ID` varchar(30) NOT NULL
);